# -*- coding: utf-8 -*-
"""IMDB Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ySrGApoOKg8LGaZnb8lRGhdLQGDQ_2u

### 1. DESCRIPTION

**Sentiment Analysis of IMDB Movie Reviews**

Dataset: IMDB Movie Reviews

Source: Hugging Face Datasets (load_dataset("imdb"))

---

Total rows (train split): 25,000

Total columns used: 2 (review_text, sentiment)

Target variable: **sentiment (positive or negative)**

---

Objective:

Build a machine learning model to classify movie reviews as positive or negative and extract actionable insights from the text.

Workflow:
1. Data Loading
2. Data Understanding
3. Data Cleaning
4. Exploratory Data Analysis (EDA)
5. Feature Engineering
6. Model Training
7. Model Evaluation
8. Business Insights
9. Conclusion

### 2. IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from collections import Counter

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.util import ngrams

from datasets import load_dataset

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
    precision_recall_curve
)

from wordcloud import WordCloud

nltk.download('stopwords')

"""### 3. LOAD DATA"""

dataset = load_dataset("imdb")

df = pd.DataFrame(dataset['train'])

df = df.rename(columns={'text': 'review_text', 'label': 'sentiment'})

df['sentiment'] = df['sentiment'].map({1: 'positive', 0: 'negative'})

df = df[['review_text', 'sentiment']]

df = df.dropna()

df = df.drop_duplicates()

df = df.reset_index(drop=True)

df.head()

"""### 4. DATA UNDERSTANDING"""

print(df.info())

print(df['sentiment'].value_counts())

plt.figure(figsize=(6, 4))
sns.countplot(x='sentiment', data=df)
plt.title("Distribution of Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

df['review_length'] = df['review_text'].apply(len)
df['word_count'] = df['review_text'].apply(lambda x: len(x.split()))

plt.figure(figsize=(6, 4))
sns.histplot(data=df, x='review_length', hue='sentiment', bins=50, kde=True)
plt.title("Review Length Distribution by Sentiment")
plt.xlabel("Number of Characters")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.boxplot(x='sentiment', y='word_count', data=df)
plt.title("Word Count by Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Word Count")
plt.tight_layout()
plt.show()

all_words_raw = " ".join(df['review_text']).lower().split()
common_words_raw = Counter(all_words_raw).most_common(20)
common_raw_df = pd.DataFrame(common_words_raw, columns=['word', 'count'])

plt.figure(figsize=(8, 4))
sns.barplot(x='count', y='word', data=common_raw_df)
plt.title("Top 20 Most Common Words (Raw Reviews)")
plt.tight_layout()
plt.show()

"""### 5. TEXT PREPROCESSING"""

stop_words = set(stopwords.words('english'))

stemmer = PorterStemmer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-z\s]", "", text)
    tokens = text.split()
    tokens = [stemmer.stem(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

df['clean_review'] = df['review_text'].apply(clean_text)

# Encode label
df['label'] = df['sentiment'].map({'positive':1, 'negative':0})

df.head()

# Most common words AFTER cleaning
all_words_clean = " ".join(df['clean_review']).split()
common_words_clean = Counter(all_words_clean).most_common(20)
common_clean_df = pd.DataFrame(common_words_clean, columns=['word', 'count'])

plt.figure(figsize=(8,4))
sns.barplot(x='count', y='word', data=common_clean_df)
plt.title("Top 20 Most Common Words (Cleaned Reviews)")
plt.show()

"""### 6. BIGRAM ANALYSIS"""

def get_top_ngrams(text_series, n=2, top=10):
    all_text = " ".join(text_series).split()
    ngram_list = list(ngrams(all_text, n))
    ngram_count = Counter(ngram_list).most_common(top)
    return [" ".join(t[0]) for t in ngram_count], [t[1] for t in ngram_count]

top_bigrams, top_bi_counts = get_top_ngrams(df['clean_review'], n=2, top=10)

plt.figure(figsize=(8, 4))
sns.barplot(x=top_bi_counts, y=top_bigrams)
plt.title("Top 10 Bigrams (Cleaned Reviews)")
plt.xlabel("Count")
plt.tight_layout()
plt.show()

"""### 7. TRAIN TEST SPLIT"""

X = df['clean_review']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""### 8. MODEL PIPELINES

**Logistic Regression**
"""

logreg_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
    ('clf', LogisticRegression(max_iter=2000, random_state=42))
])

"""**Naive Bayes**"""

nb_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
    ('clf', MultinomialNB())
])

"""### 9. CROSS VALIDATION

**Logistic Regression**
"""

logreg_cv = cross_val_score(logreg_pipeline, X_train, y_train, cv=5, scoring='roc_auc')

print("LogReg CV AUC:", logreg_cv.mean())

"""**Naive Bayes**"""

nb_cv = cross_val_score(nb_pipeline, X_train, y_train, cv=5, scoring='roc_auc')

print("Naive Bayes CV AUC:", nb_cv.mean())

"""**Best Model**"""

# Auto-select best model
model = logreg_pipeline if logreg_cv.mean() >= nb_cv.mean() else nb_pipeline
selected_name = (
    "Logistic Regression"
    if isinstance(model.named_steps['clf'], LogisticRegression)
    else "Naive Bayes"
)
print(f"Selected Model             : {selected_name}")

model.fit(X_train, y_train)

"""### 10. EVALUATION"""

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print(f"Classification Report ({selected_name})")
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Negative', 'Positive'],
            yticklabels=['Negative', 'Positive'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title(f"Confusion Matrix - {selected_name}")
plt.tight_layout()
plt.show()

# ROC Curve
roc_auc = roc_auc_score(y_test, y_prob)
fpr, tpr, _ = roc_curve(y_test, y_prob)

plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0, 1], [0, 1], '--', color='gray')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve - {selected_name}")
plt.legend()
plt.tight_layout()
plt.show()

# Precision-Recall Curve
precision, recall, _ = precision_recall_curve(y_test, y_prob)

plt.figure(figsize=(6, 4))
plt.plot(recall, precision, color='darkorange')
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title(f"Precision-Recall Curve - {selected_name}")
plt.tight_layout()
plt.show()

"""### 11. WORDCLOUD & INSIGHT"""

pos_text = " ".join(df[df['label']==1]['clean_review'])
neg_text = " ".join(df[df['label']==0]['clean_review'])

wc_pos = WordCloud(background_color="white", width=800, height=400).generate(pos_text)
plt.figure(figsize=(10, 5))
plt.imshow(wc_pos)
plt.axis("off")
plt.title("Positive Reviews — WordCloud")
plt.tight_layout()
plt.show()

wc_neg = WordCloud(background_color="black", colormap="Reds",
                   width=800, height=400).generate(neg_text)
plt.figure(figsize=(10, 5))
plt.imshow(wc_neg)
plt.axis("off")
plt.title("Negative Reviews — WordCloud")
plt.tight_layout()
plt.show()

"""### 12. TOP KEYWORDS (BUSINESS INSIGHT)"""

tfidf = model.named_steps['tfidf']
clf = model.named_steps['clf']

feature_names = tfidf.get_feature_names_out()

if isinstance(clf, LogisticRegression):
    coef = clf.coef_[0]
elif isinstance(clf, MultinomialNB):
    coef = clf.feature_log_prob_[1] - clf.feature_log_prob_[0]

top_positive = pd.Series(coef, index=feature_names).sort_values(ascending=False).head(10)
top_negative = pd.Series(coef, index=feature_names).sort_values().head(10)

print("Top Positive Words:\n", top_positive)

print("Top Negative Words:\n", top_negative)

# Visualize top keywords
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

top_positive.sort_values().plot(kind='barh', ax=axes[0], color='steelblue')
axes[0].set_title("Top 10 Positive Keywords")
axes[0].set_xlabel("Coefficient / Log Prob Ratio")

top_negative.abs().sort_values().plot(kind='barh', ax=axes[1], color='crimson')
axes[1].set_title("Top 10 Negative Keywords")
axes[1].set_xlabel("Coefficient / Log Prob Ratio (absolute)")

plt.suptitle(f"Most Influential Keywords — {selected_name}", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""### 13. TEST CUSTOM INPUT"""

def predict_sentiment_with_prob(text):
    cleaned = clean_text(text)
    prob = model.predict_proba([cleaned])[0][1]
    label = "positive" if prob >= 0.5 else "negative"
    return label, prob

test_inputs = [
    "This movie is absolutely wonderful, the acting was superb!",
    "Terrible film, complete waste of time and money.",
    "It was okay, nothing special but not bad either."
]

print("=== Custom Input Predictions ===")
for text in test_inputs:
    label, prob = predict_sentiment_with_prob(text)
    print(f"Review   : {text}")
    print(f"Sentiment: {label} (confidence: {prob:.2%})\n")

"""### 14. CONCLUSION"""

best_auc   = max(logreg_cv.mean(), nb_cv.mean())
other_auc  = min(logreg_cv.mean(), nb_cv.mean())
other_name = "Naive Bayes" if selected_name == "Logistic Regression" else "Logistic Regression"

report     = classification_report(y_test, y_pred, output_dict=True)
acc        = report['accuracy']
prec_neg   = report['0']['precision']
rec_neg    = report['0']['recall']
f1_neg     = report['0']['f1-score']
prec_pos   = report['1']['precision']
rec_pos    = report['1']['recall']
f1_pos     = report['1']['f1-score']

print(f"""

► Selected Model : {selected_name}

── Model Performance ──────────────────────────────────────────────
  Cross-Validation AUC  : {best_auc:.4f}  ({other_name}: {other_auc:.4f})
  Test Accuracy         : {acc:.2%}
  ROC-AUC (Test)        : {roc_auc:.2f}

  Class         Precision   Recall   F1-Score
  Negative      {prec_neg:.2f}        {rec_neg:.2f}     {f1_neg:.2f}
  Positive      {prec_pos:.2f}        {rec_pos:.2f}     {f1_pos:.2f}

  Confusion Matrix (Test set — 4,981 samples):
    True Negative  : 2,122  |  False Positive : 364
    False Negative : 267    |  True Positive  : 2,228

── Top Keywords ────────────────────────────────────────────────────
  Positive signals : great, excel, perfect, enjoy, love,
                     favorit, best, amaz, beauti, brilliant
  Negative signals : worst, bad, wast, aw, bore,
                     disappoint, fail, poor, noth, wors

── Key Findings ────────────────────────────────────────────────────
  • Dataset is perfectly balanced: 12,500 negative / 12,500 positive
  • Both classes have similar review length and word count distributions,
    meaning length alone is not a reliable churn signal.
  • "br" artifact from raw HTML tags dominates raw and cleaned word counts
    → indicates the need for HTML tag removal in preprocessing.
  • TF-IDF with bigrams (ngram_range=(1,2)) captures meaningful phrases
    such as "watch movi", "ever seen", and "special effect".
  • Logistic Regression significantly outperforms Naive Bayes in CV AUC
    (0.9484 vs 0.9287), confirming it as the better model for this task.

── Business Recommendations ────────────────────────────────────────
  • Use positive keywords (great, perfect, excel) in marketing campaigns
    to align messaging with what audiences genuinely praise.
  • Monitor for spikes in negative keywords (worst, bore, disappoint)
    as early warning signals of poor reception.
  • Deploy this model as a real-time review screening tool to flag
    negative feedback for priority customer service response.
  • Extend the pipeline with HTML cleaning (remove <br> tags) for
    cleaner text and potentially higher model accuracy.
""")